version: '3.7'
services:
  payer-b:
    build:
      context: .
      target: payer-b
    restart: always
    hostname: payer-b
    container_name: payer-b
    ports:
      - 8081:8081
    networks:
      - pdex
    environment:
      SERVER_PORT: "8081"
      JAVA_OPTS: '-Xmx256M -Xms128M -XX:MetaspaceSize=256M'
      PAYER-B_FHIR-SERVER-URI: ${PAYER_B_FHIR_SERVER_URI}
      PAYER-B_DATA-IMPORT_EXCLUDE-RESOURCES: MedicationDispense,AllergyIntolerance
      
      SECURITY_OAUTH2_CLIENT_CLIENT-ID: ${SECURITY_OAUTH2_CLIENT_CLIENT_ID}
      SECURITY_OAUTH2_CLIENT_CLIENT-SECRET: ${SECURITY_OAUTH2_CLIENT_CLIENT_SECRET}
      SECURITY_OAUTH2_CLIENT_ACCESS-TOKEN-URI: ${SECURITY_OAUTH2_CLIENT_ACCESS_TOKEN_URI}
      SECURITY_OAUTH2_CLIENT_USER-AUTHORIZATION-URI: ${SECURITY_OAUTH2_CLIENT_USER_AUTHORIZATION_URI}
      SECURITY_OAUTH2_RESOURCE_USER-INFO-URL: ${SECURITY_OAUTH2_RESOURCE_USER_INFO_URL}
      SECURITY_OAUTH2_CLIENT_TOKEN-NAME: "oauth_token"
      SECURITY_OAUTH2_CLIENT_CLIENT-AUTHENTICATION-SCHEME: "form"

      PAYER-A_FHIR-SERVER-URI: ${PAYER_A_FHIR_SERVER_URI}
      PAYER-A_CLIENT-ID: ${PAYER_A_CLIENT_ID}
      PAYER-A_AUTH-URI: ${PAYER_A_AUTH_URI}
      PAYER-A_TOKEN-URI: ${PAYER_A_TOKEN_URI}
      PAYER-A_SYSTEM: ${PAYER_A_SYSTEM}
      PAYER-A_REDIRECT-URI: ${PAYER_A_REDIRECT_URI}
  payer-cds-hooks-service:
    build:
      context: .
      target: payer-cds-hooks-service
    restart: always
    hostname: payer-cds-hooks-service
    container_name: payer-cds-hooks-service
    ports:
      - 8082:8082
    networks:
      - pdex
    environment:
      SERVER_PORT: "8082"
      JAVA_OPTS: '-Xmx256M -Xms128M -XX:MetaspaceSize=256M'
      PAYER_FHIR-SERVER-URI: ${PAYER_FHIR_SERVER_URI}
      PATIENT-DATA-IMPORT_SMART-APP-URI: ${PATIENT_DATA_IMPORT_SMART_APP_URI}
  provider-smart-app:
    build:
      context: .
      target: provider-smart-app
    restart: always
    hostname: provider-smart-app
    container_name: provider-smart-app
    ports:
      - 8083:8083
    networks:
      - pdex
    environment:
      SERVER_PORT: "8083"
      JAVA_OPTS: '-Xmx256M -Xms128M -XX:MetaspaceSize=256M'
      PROVIDER_FHIR-SERVER-URI: ${PROVIDER_FHIR_SERVER_URI}
      PAYER_CDS-HOOK-URI: ${PAYER_CDS_HOOK_URI}

      SECURITY_OAUTH2_CLIENT_CLIENT-ID: ${SECURITY_OAUTH2_CLIENT_CLIENT_ID}
      SECURITY_OAUTH2_CLIENT_CLIENT-SECRET: ${SECURITY_OAUTH2_CLIENT_CLIENT_SECRET}
      SECURITY_OAUTH2_CLIENT_ACCESS-TOKEN-URI: ${SECURITY_OAUTH2_CLIENT_ACCESS_TOKEN_URI}
      SECURITY_OAUTH2_CLIENT_USER-AUTHORIZATION-URI: ${SECURITY_OAUTH2_CLIENT_USER_AUTHORIZATION_URI}
      SECURITY_OAUTH2_RESOURCE_USER-INFO-URL: ${SECURITY_OAUTH2_RESOURCE_USER_INFO_URL}

      SECURITY_OAUTH2_CLIENT_TOKEN-NAME: "oauth_token"
      SECURITY_OAUTH2_CLIENT_CLIENT-AUTHENTICATION-SCHEME: "form"
      # SERVER_SSL_KEY-ALIAS: "selfsigned_localhost_sslserver"
      # SERVER_SSL_KEY-PASSWORD: "changeit"
      # SERVER_SSL_KEY-STORE: "classpath:ssl_server.jks"
      # SERVER_SSL_KEY-STORE-PROVIDER: "SUN"
      # SERVER_SSL_KEY-STORE-TYPE: "JKS"
      # SPRING_MAIN_ALLOW-BEAN-DEFENITION-OVERRIDNG: "true"
networks:
  pdex:
    name: pdex-network