version: '3.7'
services:
  payer-cds-hooks-service:
    #build: ./payer2provider/payer-cds-hooks-service
    build:
      context: .
      target: payer-cds-hooks-service
    restart: always
    hostname: payer-cds-hooks-service
    container_name: payer-cds-hooks-service
    ports:
      - 8082:8082
    networks:
      - pdex
    environment:
      SERVER_PORT: "8082"
      JAVA_OPTS: '-Xmx256M -Xms128M -XX:MetaspaceSize=256M'
      PAYER_FHIR-SERVER-URI: ${PAYER_FHIR_SERVER_URI}
      PATIENT-DATA-IMPORT_SMART-APP-URI: ${PATIENT_DATA_IMPORT_SMART_APP_URI}
  provider-smart-app:
    #build: ./payer2provider/provider-smart-app
    build:
      context: .
      target: provider-smart-app
    restart: always
    hostname: provider-smart-app
    container_name: provider-smart-app
    ports:
      - 8083:8443
    networks:
      - pdex
    environment:
      SERVER_PORT: "8443"
      JAVA_OPTS: '-Xmx256M -Xms128M -XX:MetaspaceSize=256M'
      PROVIDER_FHIR-SERVER-URI: ${PROVIDER_FHIR_SERVER_URI}
      PAYER_CDS-HOOK-URI: ${PAYER_CDS_HOOK_URI}
      SECURITY_OAUTH2_CLIENT_CLIENT-ID: "pdex-provider-smart-app"
      #SECURITY_OAUTH2_CLIENT_CLIENT-ID: ${SECURITY_OAUTH2_CLIENT_CLIENT_ID}
      SECURITY_OAUTH2_CLIENT_ACCESS-TOKEN-URI: "http://localhost:8090/realms/myrealm/protocol/openid-connect/token"
      SECURITY_OAUTH2_CLIENT_USER-AUTHORIZATION-URI: "http://localhost:8090/realms/myrealm/protocol/openid-connect/auth"
      SECURITY_OAUTH2_RESOURCE_USER-INFO-URL: "http://localhost:8090/realms/myrealm/protocol/openid-connect/userinfo"
      SECURITY_OAUTH2_CLIENT_TOKEN-NAME: "oauth_token"
      SECURITY_OAUTH2_CLIENT_CLIENT-AUTHENTICATION-SCHEME: "form"
      # SERVER_SSL_KEY-ALIAS: "selfsigned_localhost_sslserver"
      # SERVER_SSL_KEY-PASSWORD: "changeit"
      # SERVER_SSL_KEY-STORE: "classpath:ssl_server.jks"
      # SERVER_SSL_KEY-STORE-PROVIDER: "SUN"
      # SERVER_SSL_KEY-STORE-TYPE: "JKS"
      SPRING_MAIN_ALLOW-BEAN-DEFENITION-OVERRIDNG: "true"
networks:
  pdex:
    name: pdex-network